POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer USERIN TOKEN TÄHÄN

{
    "title": "Tean viides blogi",
    "author": "Tea",
    "url": "https://fi.wikipedia.org/wiki/Blogi",
    "likes": 4
}